// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAt1uBfgKV8hE3OMQVlaHZmZAJe4ZLjO9Y',
    appId: '1:921595841854:web:d38a61db72e53ea4a9b06f',
    messagingSenderId: '921595841854',
    projectId: 'order-pizza-dfdfe',
    authDomain: 'order-pizza-dfdfe.firebaseapp.com',
    storageBucket: 'order-pizza-dfdfe.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXE-MOr4k7ibYIJDihebGNTkvAmbn3Q64',
    appId: '1:921595841854:android:795bb3d489db6e17a9b06f',
    messagingSenderId: '921595841854',
    projectId: 'order-pizza-dfdfe',
    storageBucket: 'order-pizza-dfdfe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPo5WcdmbZs7A6ksxDUJecOocI0truoyY',
    appId: '1:921595841854:ios:b58f229cc48b0adba9b06f',
    messagingSenderId: '921595841854',
    projectId: 'order-pizza-dfdfe',
    storageBucket: 'order-pizza-dfdfe.firebasestorage.app',
    iosBundleId: 'com.example.orderPizza',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPo5WcdmbZs7A6ksxDUJecOocI0truoyY',
    appId: '1:921595841854:ios:b58f229cc48b0adba9b06f',
    messagingSenderId: '921595841854',
    projectId: 'order-pizza-dfdfe',
    storageBucket: 'order-pizza-dfdfe.firebasestorage.app',
    iosBundleId: 'com.example.orderPizza',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAt1uBfgKV8hE3OMQVlaHZmZAJe4ZLjO9Y',
    appId: '1:921595841854:web:2325069b3c4dc181a9b06f',
    messagingSenderId: '921595841854',
    projectId: 'order-pizza-dfdfe',
    authDomain: 'order-pizza-dfdfe.firebaseapp.com',
    storageBucket: 'order-pizza-dfdfe.firebasestorage.app',
  );

}